{
 "title": "CCX Processing SLO",
 "description": "A dashboard to monitor CCX Processing team SLO",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "ccx-data-pipeline-stage,ccx-data-pipeline-prod"
   },
   { "name": "aws_msk", "query": "prometheus" },
   { "name": "slo_response_time_seconds", "label": "SLO response time limit", "query": "0.1,0.2,0.3,0.4,0.5" },
   {
    "name": "services",
    "label": "services",
    "query": ".*db-writer-.*|.*cache-writer-.*|.*dvo-writer-.*|ccx-data-pipeline-.*|dvo-extractor-.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Total time to process an archive",
   "type": "stat",
   "description": "Total time for processing an archive since it gets to the pipeline until the report is stored in the database",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n    increase(successful_messages_processing_time_sum{service=\"ccx-insights-results-db-writer-prometheus-exporter\",namespace=\"$namespace\"}[1m])\n  )\n  /\n  sum(\n    increase(successful_messages_processing_time_count{service=\"ccx-insights-results-db-writer-prometheus-exporter\",namespace=\"$namespace\"}[1m])\n  )\n) + (\n  sum(\n    increase(ccx_process_duration_seconds_sum{service=\"ccx-data-pipeline-prometheus-exporter\",namespace=\"$namespace\"}[1m])\n  )\n  /\n  sum(\n    increase(ccx_process_duration_seconds_count{service=\"ccx-data-pipeline-prometheus-exporter\",namespace=\"$namespace\"}[1m])\n  )\n)"
    }
   ]
  },
  {
   "title": "Total Kafka lag",
   "type": "stat",
   "description": "Total Kafka lag including the one in the ccx-data-pipeline and the db-writer.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aws_kafka_estimated_max_time_lag_sum{topic=~\".*platform.upload.announce\", consumer_group=\"ccx_data_pipeline_app\"}) + sum(aws_kafka_estimated_max_time_lag_sum{topic=~\".*ccx.ocp.results\", consumer_group=\"ccx_data_pipeline_app\"})"
    }
   ]
  },
  {
   "title": "Request time greater than $slo_response_time_seconds s",
   "type": "stat",
   "description": "Percentage of requests that has a request time greater than slo_response_time_seconds seconds",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "( count ( rate(api_endpoints_response_time_sum{namespace=\"$namespace\", service=\"ccx-smart-proxy\"}[1m]) > $slo_response_time_seconds ) \n/\nsum(rate(api_endpoints_response_time_count{namespace=\"$namespace\", service=\"ccx-smart-proxy\"}[1m])) ) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Responses with 500 status code",
   "type": "stat",
   "description": "Percentage of responses with a status code 500",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_endpoints_status_codes{namespace=\"$namespace\", service=\"ccx-smart-proxy\", status_code=\"500\"}[1m]))\n/\nsum(rate(api_endpoints_requests{namespace=\"$namespace\", service=\"ccx-smart-proxy\"}[1m]))"
    }
   ]
  },
  {
   "title": "Archive processors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ccx_consumer_received_total{namespace=\"$namespace\", pod=~\"$services\"}[1m])) by (service)",
     "legendFormat": "Received: {{service}}"
    },
    {
     "expr": "sum(increase(ccx_downloaded_total_count{namespace=\"$namespace\", pod=~\"$services\"}[1m])) by (service)",
     "legendFormat": "Downloaded: {{service}}"
    },
    {
     "expr": "sum(increase(ccx_engine_processed_total{namespace=\"$namespace\", pod=~\"$services\"}[1m])) by (service)",
     "legendFormat": "Processed: {{service}}"
    },
    {
     "expr": "sum(increase(ccx_published_total{namespace=\"$namespace\", pod=~\"$services\"}[1m])) by (service)",
     "legendFormat": "Published: {{service}}"
    }
   ]
  },
  {
   "title": "Kafka lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_kafka_estimated_max_time_lag_sum{consumer_group=~\"ccx_cache_writer_app|ccx_data_pipeline_app|ccx_notification_app|dvo_extractor_app|dvo_writer_app\"}) by (consumer_group, topic)",
     "legendFormat": "{{consumer_group}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Average Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  increase(ccx_process_duration_seconds_sum{namespace=\"$namespace\", service=~\"$services\"}[1m])\n) by (service)\n/\nsum(\n  increase(ccx_process_duration_seconds_count{namespace=\"$namespace\", service=~\"$services\"}[1m])\n) by (service)",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum(\n  increase(successful_messages_processing_time_sum{namespace=\"$namespace\", service=~\"$services\"}[1m])\n) by (container)\n/\nsum(\n  increase(successful_messages_processing_time_count{namespace=\"$namespace\", service=~\"$services\"}[1m])\n) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Writers - Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(consumed_messages{service=~\"$services\", namespace=\"$namespace\"}[1m])) by (container)",
     "legendFormat": "Consumed: {{container}}"
    },
    {
     "expr": "sum(increase(written_reports{service=~\"$services\",namespace=\"$namespace\"}[1m])) by (container)",
     "legendFormat": "Written: {{container}}"
    },
    {
     "expr": "sum(increase(consuming_errors{service=~\"$services\", namespace=\"$namespace\"}[1m])) by (container)",
     "legendFormat": "Errors: {{container}}"
    },
    {
     "expr": "sum(increase(produced_messages{service=~\"$services\",namespace=\"$namespace\"}[1m])) by (container)",
     "legendFormat": "Produced: {{container}}"
    }
   ]
  },
  {
   "title": "Smart Proxy - Response Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status_code)(increase(api_endpoints_status_codes{namespace=\"$namespace\", service=\"ccx-smart-proxy\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{status_code}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "On-demand data gathering API - Response Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status_code)(increase(api_endpoints_status_codes{namespace=\"$namespace\", service=\"ccx-smart-proxy\", exported_endpoint=~\".*request.*\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{status_code}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "description": "Please visit the \"CCX Cronjobs\" dashboard for more details",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kube_cronjob_status_active{namespace=\"$namespace\"}) by(cronjob)",
     "legendFormat": "{{cronjob}}"
    }
   ]
  },
  {
   "title": "Smart Proxy - Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(exported_endpoint)(rate(api_endpoints_response_time_sum{namespace=\"$namespace\", service=\"ccx-smart-proxy\"}[5m]) / rate(api_endpoints_response_time_count{namespace=\"$namespace\", service=\"ccx-smart-proxy\"}[5m])) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_endpoint}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}