{
 "title": "CCX Archive Processors",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "ccx-data-pipeline-stage,ccx-data-pipeline-prod"
   },
   {
    "name": "services",
    "label": "services",
    "query": "ccx-data-pipeline-.*|dvo-extractor-.*"
   },
   {
    "name": "consumer_groups",
    "label": "consumer_groups",
    "query": "ccx_data_pipeline_app|dvo_extractor_app"
   },
   {
    "name": "aws_msk",
    "label": "Datasource used for AWS MSK metrics",
    "query": "prometheus"
   }
  ]
 },
 "panels": [
  {
   "title": "Number Of Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (up{namespace=\"$namespace\", pod=~\"$services\"}) by (service)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{service}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Archives (Past Day)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ccx_consumer_received_total{namespace=\"$namespace\", pod=~\"$services\"}[1d])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Published Results (Past Day)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ccx_published_total{namespace=\"$namespace\", pod=~\"$services\"}[1d])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Failures (Past Week)",
   "type": "stat",
   "description": "Number of OCP engine failures (unsuccessfully processed archives) in the past week.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ccx_failures_total{namespace=\"$namespace\", pod=~\"$services\"}[1w])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Unhandled (Past Week)",
   "type": "stat",
   "description": "Number of unhandled Kafka messages in the past week.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ccx_not_handled_total{namespace=\"$namespace\", pod=~\"$services\"}[1w])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Lag increase per hour",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_kafka_estimated_max_time_lag_sum{topic=~\".*platform.upload.announce\", consumer_group=~\"$consumer_groups\"}) by (consumer_group, topic) - sum(aws_kafka_estimated_max_time_lag_sum{topic=~\".*platform.upload.announce\", consumer_group=~\"$consumer_groups\"} offset 1h) by (consumer_group, topic)",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  },
  {
   "title": "Received Events per 1 Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Number of Events" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ccx_consumer_received_total{namespace=\"$namespace\", pod=~\"$services\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Downloaded Events per 1 Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Number of Events" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ccx_downloaded_total_count{namespace=\"$namespace\", pod=~\"$services\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Processed Events per 1 Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Number of Events" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ccx_engine_processed_total{namespace=\"$namespace\", pod=~\"$services\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Published Events per 1 Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Number of Events" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ccx_published_total{namespace=\"$namespace\", pod=~\"$services\"}[1m])) by (service )",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Kafka lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_kafka_estimated_max_time_lag_sum{topic=~\".*platform.upload.announce\",consumer_group=~\"$consumer_groups\"}) by (consumer_group, topic)",
     "legendFormat": "{{consumer_group}}: {{topic}}"
    }
   ]
  },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$services\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=\"\",namespace=\"$namespace\",pod=~\"$services\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Seconds to Process a Single Archive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Number of Occurrences" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.5\", pod=~\"$services\"})",
     "legendFormat": "( -Inf; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"1.0\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.5\", pod=~\"$services\"})",
     "legendFormat": "( 0.5; 1.0 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"2.0\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"1.0\", pod=~\"$services\"})",
     "legendFormat": "( 1.0; 2.0 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"2.0\", pod=~\"$services\"})",
     "legendFormat": "( 2.0; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", pod=~\"$services\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  },
  {
   "title": "Seconds to Download a Single Archive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Number of Occurrences" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.1\", pod=~\"$services\"})",
     "legendFormat": "( -Inf; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.25\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.1\", pod=~\"$services\"})",
     "legendFormat": "( 0.1; 0.25 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.5\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.25\", pod=~\"$services\"})",
     "legendFormat": "( 0.25; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.75\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.5\", pod=~\"$services\"})",
     "legendFormat": "( 0.5; 0.75 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"1.0\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.75\", pod=~\"$services\"})",
     "legendFormat": "( 0.75; 1.0 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"1.0\", pod=~\"$services\"})",
     "legendFormat": "( 1.0; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", pod=~\"$services\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  },
  {
   "title": "Seconds to Publish a Single Archive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Number of Occurrences" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.005\", pod=~\"$services\"})",
     "legendFormat": "( -Inf; 0.005 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.01\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.005\", pod=~\"$services\"})",
     "legendFormat": "( 0.005; 0.01 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.025\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.01\", pod=~\"$services\"})",
     "legendFormat": "( 0.01; 0.025 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.1\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.025\", pod=~\"$services\"})",
     "legendFormat": "( 0.025; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.5\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.1\", pod=~\"$services\"})",
     "legendFormat": "( 0.1; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.5\", pod=~\"$services\"})",
     "legendFormat": "( 0.5; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\", pod=~\"$services\", pod=~\"$services\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", pod=~\"$services\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  }
 ]
}