{
 "title": "CCX Cronjobs",
 "description": "https://issues.redhat.com/browse/CCXDEV-14570",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "ccx-data-pipeline-stage,ccx-data-pipeline-prod"
   }
  ]
 },
 "panels": [
  {
   "title": "Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_cronjob_info{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_cronjob_status_active{namespace=\"$namespace\"}) by(cronjob)",
     "legendFormat": "{{cronjob}}"
    }
   ]
  },
  {
   "title": "Time till completion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max((\n  max by (job_name) (kube_job_status_completion_time{namespace=\"$namespace\"}) - max by (job_name) (kube_job_status_start_time{namespace=\"$namespace\"})\n) * on(job_name) group_left(owner_name) kube_job_owner{namespace=\"$namespace\", owner_kind=\"CronJob\", owner_name!=\"\"}) by(owner_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failing jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (owner_name) (\n  max by (job_name) (\n    max_over_time(kube_job_status_failed{namespace=\"$namespace\"}[1h])\n  )\n  * on(job_name) group_left(owner_name)\n  max by (job_name, owner_name) (\n    kube_job_owner{namespace=\"$namespace\", owner_kind=\"CronJob\", owner_name!=\"\"}\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}